//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::projects::Entity as Projects;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
pub use super::workpace_members::Entity as WorkpaceMembers;
pub use super::workspaces::Entity as Workspaces;
